name: Publish

on:
  release:
    types: [published]
    
jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore /p:Version=${{ github.event.release.tag_name }} -p:PackageReleaseNotes="See https://github.com/Noggog/Synthesis/releases/tag/${{ github.event.release.tag_name }}"
    - name: Test
      run: dotnet test --no-build -c Release    
    - name: Pack
      run: dotnet publish "Synthesis.Bethesda.GUI/Synthesis.Bethesda.GUI.csproj" -r win-x64 -f netcoreapp3.1 /p:PublishSingleFile=True --self-contained false --configuration Release /p:IncludeSymbolsInSingleFile=true
    - name: Publish Synthesis GUI to Github
      uses: svenstaro/upload-release-action@v2
      with:
        file: Synthesis.Bethesda.GUI/bin/Release/netcoreapp3.1/win-x64/publish/Synthesis.exe
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.release.tag_name }}
    - name: Publish Nugets to Github
      uses: svenstaro/upload-release-action@v2
      with:
        file: "**/*.nupkg"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.release.tag_name }}
        file_glob: "true"
    - name: Publish Nugets to Nuget.org
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols true
