name: Wiki

on:
  push:
    branches: [ dev ]
    paths:
      - 'README.md'
      - 'docs/**'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN_WIKI }}
      # Additional steps to generate documentation in "Documentation" directory
      - name: github-docs-to-wiki
        uses: cmbrose/github-docs-to-wiki@v0.24
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN_WIKI }}
          rootDocsFolder: "docs/"
